### ISSUE TITLE
Could I translate this article to Chinese ?

### ISSUE THREAD

**Issue by koreQAQ** [baraldor/defi#3]
Hello，bro

I am a beginner of DeFi and am glad to read this article.

I would like to translate this article into Chinese so as to provide direction for those with relevant needs in our country.

Could I translate this article to Chinese ?

**Comment by baraldor** [comment]
Absolutely!! I'd recommend:
- reaching out to the authors of each article as you translate them, 
- always remember to include the references,
- and make it open source too

As for my part, feel free to translate it and spread the word.

**Comment by koreQAQ** [comment]
> Absolutely!! I'd recommend:
> 
> * reaching out to the authors of each article as you translate them,
> * always remember to include the references,
> * and make it open source too
> 
> As for my part, feel free to translate it and spread the word.  

@baraldor 
Bro，thank for your advice 
And I will submit a PR in the near future.
